# BASE DE DATOS EMPRESAS
ALTER TABLE  `empresas` 
ADD  `Iban` VARCHAR( 34 ) NULL ,
ADD  `Bic` VARCHAR( 11 ) NULL;

# INQUILINOS
ALTER TABLE  `inquilinos` 
ADD  `Iban` VARCHAR( 34 ) NULL ,
ADD  `Bic` VARCHAR( 11 ) NULL,
ADD  `Mandato` VARCHAR( 35 ) NULL ,
ADD  `FechaMandato` DATE NOT NULL DEFAULT  '0000-00-00';

# INMUEBLES
ALTER TABLE  `inmuebles` 
ADD  `Iban` VARCHAR( 34 ) NULL ,
ADD  `Bic` VARCHAR( 11 ) NULL,
ADD  `Mandato` VARCHAR( 35 ) NULL ,
ADD  `FechaMandato` DATE NOT NULL DEFAULT  '0000-00-00';

# BASE DE DATOS DE CADA EMPRESA
ALTER TABLE  `recibos` 
ADD  `IbanCargo` VARCHAR( 34 ) NULL ,
ADD  `BicCargo` VARCHAR( 11 ) NULL,
ADD  `IbanAbono` VARCHAR( 34 ) NULL ,
ADD  `BicAbono` VARCHAR( 11 ) NULL,
ADD  `Mandato` VARCHAR( 35 ) NULL ,
ADD  `FechaMandato` DATE NOT NULL DEFAULT  '0000-00-00';

